import type { StrategyTable } from "./types";

function fullRow(action: "H" | "S") {
  return {
    "2": action,
    "3": action,
    "4": action,
    "5": action,
    "6": action,
    "7": action,
    "8": action,
    "9": action,
    "10": action,
    A: action,
  } as const;
}

export const mvpS17StrategyTable: StrategyTable = {
  metadata: {
    name: "blackjack-mvp-s17",
    dealerSoft17: "stand",
    deckCount: 6,
    notes:
      "No-split MVP strategy table for hard/soft totals (6-deck, S17, double on any first two cards).",
  },
  hard: {
    "4": fullRow("H"),
    "5": fullRow("H"),
    "6": fullRow("H"),
    "7": fullRow("H"),
    "8": fullRow("H"),
    "9": {
      "2": "H",
      "3": "D",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "10": {
      "2": "D",
      "3": "D",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "D",
      "8": "D",
      "9": "D",
      "10": "H",
      A: "H",
    },
    "11": {
      "2": "D",
      "3": "D",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "D",
      "8": "D",
      "9": "D",
      "10": "D",
      A: "H",
    },
    "12": {
      "2": "H",
      "3": "H",
      "4": "S",
      "5": "S",
      "6": "S",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "13": {
      "2": "S",
      "3": "S",
      "4": "S",
      "5": "S",
      "6": "S",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "14": {
      "2": "S",
      "3": "S",
      "4": "S",
      "5": "S",
      "6": "S",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "15": {
      "2": "S",
      "3": "S",
      "4": "S",
      "5": "S",
      "6": "S",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "16": {
      "2": "S",
      "3": "S",
      "4": "S",
      "5": "S",
      "6": "S",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "17": fullRow("S"),
    "18": fullRow("S"),
    "19": fullRow("S"),
    "20": fullRow("S"),
    "21": fullRow("S"),
  },
  soft: {
    "12": fullRow("H"),
    "13": {
      "2": "H",
      "3": "H",
      "4": "H",
      "5": "D",
      "6": "D",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "14": {
      "2": "H",
      "3": "H",
      "4": "H",
      "5": "D",
      "6": "D",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "15": {
      "2": "H",
      "3": "H",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "16": {
      "2": "H",
      "3": "H",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "17": {
      "2": "H",
      "3": "D",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "H",
      "8": "H",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "18": {
      "2": "S",
      "3": "D",
      "4": "D",
      "5": "D",
      "6": "D",
      "7": "S",
      "8": "S",
      "9": "H",
      "10": "H",
      A: "H",
    },
    "19": fullRow("S"),
    "20": fullRow("S"),
    "21": fullRow("S"),
  },
};
